# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('size', models.IntegerField(default=0)),
                ('guid', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('search_string', models.CharField(max_length=200)),
                ('additional_parameters', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('date_key', models.CharField(db_index=True, max_length=20)),
                ('ignored', models.BooleanField(default=False)),
                ('file', models.CharField(max_length=1000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderlist.SearchGroup')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderlist.SearchResult'),
        ),
    ]
