# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=4000)),
            ],
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spiderlist.MatchedFile'),
        ),
    ]
