# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderlist', '0003_searchresult_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedfile',
            name='date_key',
            field=models.CharField(db_index=True, default='0.0.0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchedfile',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='spiderlist.SearchGroup'),
            preserve_default=False,
        ),
    ]
