# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderlist', '0005_matchedfile_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='key',
            field=models.CharField(default='4ae85251b4733021a9ff97d9df6c3c22', max_length=40),
        ),
        migrations.AddField(
            model_name='report',
            name='url',
            field=models.CharField(default='https://nzb.cat/', max_length=400),
        ),
    ]
